language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -U importlib_metadata black
- black --check .
- pip install .
script: pytest
deploy:
  provider: pypi
  user: tommyclark
  password: $PYPI_PASS
  on:
    branch: master
    python: '3.7'